// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvWGODq5IQGaPgImXvhKxBV8P4xqkUuUg',
    appId: '1:1000781957245:web:ade028d34a1f78542e0914',
    messagingSenderId: '1000781957245',
    projectId: 'eslam-elsaidy',
    authDomain: 'eslam-elsaidy.firebaseapp.com',
    storageBucket: 'eslam-elsaidy.firebasestorage.app',
    measurementId: 'G-LW6P42030L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpgjML_enOw4PI9zwZ63kF5UU_HdfClI',
    appId: '1:1000781957245:android:a620ea40783529b22e0914',
    messagingSenderId: '1000781957245',
    projectId: 'eslam-elsaidy',
    storageBucket: 'eslam-elsaidy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEkmvpVbNPmWselZWHrFA6nyk46PbDw2o',
    appId: '1:1000781957245:ios:467388591e3183352e0914',
    messagingSenderId: '1000781957245',
    projectId: 'eslam-elsaidy',
    storageBucket: 'eslam-elsaidy.firebasestorage.app',
    iosBundleId: 'com.app.eslamelsa3dyactivecourses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEkmvpVbNPmWselZWHrFA6nyk46PbDw2o',
    appId: '1:1000781957245:ios:467388591e3183352e0914',
    messagingSenderId: '1000781957245',
    projectId: 'eslam-elsaidy',
    storageBucket: 'eslam-elsaidy.firebasestorage.app',
    iosBundleId: 'com.app.eslamelsa3dyactivecourses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvWGODq5IQGaPgImXvhKxBV8P4xqkUuUg',
    appId: '1:1000781957245:web:a0190475b857a5022e0914',
    messagingSenderId: '1000781957245',
    projectId: 'eslam-elsaidy',
    authDomain: 'eslam-elsaidy.firebaseapp.com',
    storageBucket: 'eslam-elsaidy.firebasestorage.app',
    measurementId: 'G-1WG8EVM46X',
  );

}